export const educationContent = [
  {
    title: 'UOC: Univesitat Oberta de Catalunya',
    year: '2024',
    description: 'Computer Science (Currently studying)',
    logoImage: '/assets/educationLogos/uocLogo.webp',
    logoImageDescription: 'UOC: Univesitat Oberta de Catalunya logo',
  },
  {
    title: 'Ilerna FP',
    year: '2020 - 2022',
    description: 'Web Application Development Studies',
    logoImage: '/assets/educationLogos/ilernaLogo.webp',
    logoImageDescription: 'Ilerna FP: Web Application Development Studies logo',
  },
  {
    title: 'Lemoncode',
    year: '2022',
    description: 'Backend Bootcamp',
    logoImage: '/assets/educationLogos/lemoncodeLogo.webp',
    logoImageDescription: 'Lemoncode logo',
  },
  {
    title: 'UNIR: Fundación Universitaria Internacional de La Rioja',
    year: '2019 - 2020',
    description: 'Pre-phd Musical Research',
    logoImage: '/assets/educationLogos/unirLogo.webp',
    logoImageDescription: 'UNIR: Fundación Universitaria Internacional de La Rioja logo',
  },
  {
    title: 'Universidad de Murcia',
    year: '2016 - 2017',
    description: 'Post-grade in Mediation and Conflict Resolution',
    logoImage: '/assets/educationLogos/universidadDeMurciaLogo.webp',
    logoImageDescription: 'Universidad de Murcia logo',
  },
  {
    title: 'VIU: Universidad Internacional de Valencia',
    year: '2019 - 2020',
    description: "Master's Degree in Teaching",
    logoImage: '/assets/educationLogos/viuLogo.webp',
    logoImageDescription: 'VIU: Universidad Internacional de Valencia logo',
  },
  {
    title: 'Paris CRR Conservatory',
    year: '2016 - 2018',
    description: 'Bachelor: Classical Percussion Studies',
    logoImage: '/assets/educationLogos/crrLogo.webp',
    logoImageDescription: 'Paris CRR Conservatory logo',
  },
  {
    title: 'Institut Joan Llongueres',
    year: '2014 - 2016',
    description: 'Post-grade in Dalcroze Rhythmics Studies',
    logoImage: '/assets/educationLogos/joanLlongueresLogo.webp',
    logoImageDescription: 'Institut Joan Llongueres logo',
  },
  {
    title: 'Barcelona Liceu Conservatory',
    year: '2020',
    description: 'Bachelor: Jazz Percussion Studies',
    logoImage: '/assets/educationLogos/liceuLogo.webp',
    logoImageDescription: 'Liceu Conservatory logo',
  },
];
